// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsx2E0wwBHup586l6AzpvC5ZG0EcbLFAw',
    appId: '1:24360852719:android:37a76adddc9c22f1f14f1a',
    messagingSenderId: '24360852719',
    projectId: 'runmate-252e5',
    authDomain: 'runmate-252e5.firebaseapp.com',
    databaseURL: 'https://runmate-252e5-default-rtdb.firebaseio.com',
    storageBucket: 'runmate-252e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-r5EBE9yjZtFXn6sOAgkiZ-RCk5HIvM',
    appId: '1:24360852719:ios:78097c986b5999ecf14f1a',
    messagingSenderId: '24360852719',
    projectId: 'runmate-252e5',
    databaseURL: 'https://runmate-252e5-default-rtdb.firebaseio.com',
    storageBucket: 'runmate-252e5.firebasestorage.app',
    iosBundleId: 'com.xorgeek.runmate',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsx2E0wwBHup586l6AzpvC5ZG0EcbLFAw',
    appId: '1:24360852719:android:37a76adddc9c22f1f14f1a',
    messagingSenderId: '24360852719',
    projectId: 'runmate-252e5',
    databaseURL: 'https://runmate-252e5-default-rtdb.firebaseio.com',
    storageBucket: 'runmate-252e5.firebasestorage.app',
  );
}
