// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-H020Uul_SNcekGeVnr0uESLg713rEA',
    appId: '1:157462453434:web:57233170ff3a84ca4c7683',
    messagingSenderId: '157462453434',
    projectId: 'medishop-40923',
    authDomain: 'medishop-40923.firebaseapp.com',
    databaseURL: 'https://medishop-40923-default-rtdb.firebaseio.com',
    storageBucket: 'medishop-40923.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIy9zgNxqriEeM-DFTvm-SM1zi6b74FZw',
    appId: '1:157462453434:ios:16b4826f28f07cf04c7683',
    messagingSenderId: '157462453434',
    projectId: 'medishop-40923',
    databaseURL: 'https://medishop-40923-default-rtdb.firebaseio.com',
    storageBucket: 'medishop-40923.firebasestorage.app',
    iosClientId: '157462453434-eke8vafdhitj3ftdhp6ihhvgccgci84o.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMap',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTrj-Z_zrOqdrAzfeibKGvHHDiV7cQuRc',
    appId: '1:157462453434:android:fb87af59b08a4ec74c7683',
    messagingSenderId: '157462453434',
    projectId: 'medishop-40923',
    databaseURL: 'https://medishop-40923-default-rtdb.firebaseio.com',
    storageBucket: 'medishop-40923.firebasestorage.app',
  );
}
